force-app/main/default/objects/Service_Subscription__c/Service_Subscription__c.object-meta.xml
<CustomObject>
    <label>Service_Subscription</label>
    <nameField>
        <label>Service_Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service_SubscriptionS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service_SubscriptionS</relationshipLabel>
    <relationshipName>Service_SubscriptionS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountService.cls
public class AccountService {
    public static void serviceUpdate(set<Id>accountIds){
         List<Service_Subscription__c>sslist=new List<Service_Subscription__c>();
        List<Service_Subscription__c>serviceToUpdate=[select id,Status__c from Service_Subscription__c where
                                                	Account__c IN:accountIds];
        for(Service_Subscription__c service:serviceToUpdate){
            service.Status__c='Suspended';
            sslist.add(service);
        }
        if(!sslist.isEmpty()){
            update sslist;
        }
    }
}