force-app/main/default/objects/Service_Subscription__c/Service_Subscription__c.object-meta.xml
<CustomObject>
    <label>Service_Subscription</label>
    <nameField>
        <label>Service_Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service_SubscriptionS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ServiceSubscriptionExpiryBatch.cls
global class ServiceSubscriptionExpiryBatch implements Database.Batchable<Sobject>{
    global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator([select Id,	Expiry_Date__c,	Status__c from Service_Subscription__c
                                           where Status__c='Active' and Expiry_Date__c < TODAY] );
    }
    
    global void execute(Database.BatchableContext bc,List<Service_Subscription__c>scope){
        for(Service_Subscription__c ss : scope){
            ss.Status__c ='Expired';
        }
        update scope;
    }
    global void finish(Database.BatchableContext bc){
        system.debug('service subscription expiry batch completed');
    }
}