force-app/main/default/objects/Service_Subscription__c/Service_Subscription__c.object-meta.xml
<CustomObject>
    <label>Service_Subscription</label>
    <nameField>
        <label>Service_Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service_SubscriptionS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service_SubscriptionS</relationshipLabel>
    <relationshipName>Service_SubscriptionS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Subscription__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <label>Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Basic</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Subscription__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>Fiber</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/cutsomer360_1.cls
public with sharing class cutsomer360_1 {
   @AuraEnabled(Cacheable=true)
   public static List<Service_Subscription__c> getRecords(Id accountId){
    return[select Id,Name,
               Service_Type__c,
               Plan__c,
               Status__c
        FROM Service_Subscription__c where 	Account__c =:accountId];
   }

   @AuraEnabled 
   public static void updateRecords(List<Service_Subscription__c>services){
    update services;
    }
    @AuraEnabled 
     public static void deleteRecord(Id serviceId) {
        
        Service_Subscription__c service = [
            SELECT Id
            FROM Service_Subscription__c
            WHERE Id = :serviceId
            LIMIT 1
        ];

        delete service;
    }
}